<?php

$cividictus =
[
    "en" =>
    [
        "ancient_era" => "Ancient Era",
        "classical_era" => "Classical Era",
        "medieval_era" => "Medieval Era",
        "renaissance_era" => "Renaissance Era",
        "industrial_era" => "Industrial Era",
        "modern_era" => "Modern Era",
        "atomic_era" => "Atomic Era",
        "information_era" => "Information Era",
        "future_era" => "Future Era",
        "space_era" => "Space Era",
        "de" => "of the",
        "chiefdom" => "Chiefdom",
        "autocracy" => "Autocracy",
        "oligarchy" => "Oligarchy",
        "classical_republic" => "Classical Republic",
        "monarchy" => "Monarchy",
        "theocracy" => "Theocracy",
        "merchant_republic" => "Merchant Republic",
        "fascism" => "Fascism",
        "communism" => "Communism",
        "democracy" => "Democracy",
        "natural_economy" => "Natural Economy",
        "free_market" => "Free Market",
        "fair_market" => "Fair Market",
        "planned_economy" => "Planned Economy",
        "king" => "King",
        "queen" => "Queen",
        "prince" => "Prince",
        "princess" => "Princess",
        "duke" => "Duke",
        "duchess" => "Duchess",
        "caesar" => "Tsar",
        "emperor" => "Emperor",
        "empress" => "Empress",
        "president" => "President",
    ],
    "la" =>
    [
        "ancient_era" => "Antiquitas",
        "classical_era" => "Antiquitas Classica",
        "medieval_era" => "Medium Aevum",
        "renaissance_era" => "Aevum Renascentiae",
        "industrial_era" => "Aevum Industrialis",
        "modern_era" => "Aevum Recentissimum",
        "atomic_era" => "Aevum Atomicum",
        "information_era" => "Aevum Scientiae",
        "future_era" => "Aevum Futurum",
        "space_era" => "Aevum Spatio",
        "de" => "de",
        "chiefdom" => "Principatus",
        "autocracy" => "Autocratia",
        "oligarchy" => "Oligarchia",
        "classical_republic" => "Res Publica Classica",
        "monarchy" => "Monarchia",
        "theocracy" => "Theocratia",
        "merchant_republic" => "Mercator Rem Publicam",
        "fascism" => "Fascismus",
        "communism" => "Communismus",
        "democracy" => "Democratia",
        "natural_economy" => "Naturalis Oeconomia",
        "free_market" => "Liberum Forum",
        "fair_market" => "Aequum Forum",
        "planned_economy" => "Cogitavit Oeconomia",
        "king" => "Rex",
        "queen" => "Regina",
        "prince" => "Princeps",
        "princess" => "Regia Puella",
        "duke" => "Dux",
        "duchess" => "Ducissa",
        "caesar" => "Caesar",
        "emperor" => "Imperator",
        "empress" => "Imperatrix",
        "president" => "Praesidens",
    ],
];
